### ISSUE TITLE
cmd vs Powershell

### ISSUE THREAD

**Issue by DeFlanko** [Mijago/D2StatCollector#10]
I noticed that when trying to run "docker compose up" in CMD Windows 11  it was throwing error. 

While in Powershell it worked as expected. 

![image](https://user-images.githubusercontent.com/5233969/232253083-ec004ed9-3204-4160-ade3-fdc701ca753f.png)

also, had to run that command in the folder ./D2StatCollector-master/  -- not sure if that should be specified or not in the install notes.

**Comment by Mijago** [comment]
Hi!

> While in Powershell it worked as expected.

Probably some setup errors, sometimes the consoles use different PATH variables, so it might not see some things, or permissions may be messed up. As you did not specify the errors, I guess that it is one of these things. 



> had to run that command in the folder ./D2StatCollector-master/ 

This is a must-be, as docker must know which docker-compose.yml you want to use. Per default, it uses the file in the local directory, hence you must be in that directory.

**Comment by DeFlanko** [comment]
Thansk @Mijago
