### ISSUE TITLE
importing example uses legacy UID

### ISSUE THREAD

**Issue by DeFlanko** [Mijago/D2StatCollector#11]
If you import your example dashboard into Grafana, you have to replace its uid "I9EdXRL4z" with the newly installed DB uid.

to do that, create a temporary new dashboard, edit it and view its JSON and copy _that_ UID.

Go back to the imported "User stats" dashboard and edit that -- find and replace "I9EdXRL4z" (CTRL+H) with the uid you just got from the temp dashboard. 

Save.

Then it will show your dashboard!

![image](https://user-images.githubusercontent.com/5233969/232253953-5bbad208-1b7e-497b-969a-39b38f12641e.png)

**Comment by Mijago** [comment]
New exported files can be found here: 
- https://github.com/Mijago/D2StatCollector/tree/master/doc/grafana-examples
- https://github.com/Mijago/D2StatCollector/blob/master/doc/grafana-examples/User%20Stats.json

**Comment by DeFlanko** [comment]
The newly imported worked without editing.

 
![image](https://user-images.githubusercontent.com/5233969/232255526-2e812639-8b78-4408-bc3d-509e5cc75121.png)
