### ISSUE TITLE
Not all data showing up in Dashboard

### ISSUE THREAD

**Issue by DeFlanko** [Mijago/D2StatCollector#12]
Is it possible that I have API setup wrong?

![image](https://user-images.githubusercontent.com/5233969/232254945-886f7f01-b2eb-487c-a8a6-8695eea57227.png)

![image](https://user-images.githubusercontent.com/5233969/232255055-8e95d1e0-265e-458a-a9c8-ccf57d03bf59.png)

**Comment by Mijago** [comment]
These are just for login, as we do not use the login here, those should not have any effect.

My first guess would be that the dashboard import ruined something :/ 
I just used the real `export` feature in Grafana and pushed the files here - please give them a try! 
https://github.com/Mijago/D2StatCollector/tree/master/doc/grafana-examples

**Comment by DeFlanko** [comment]
Question, is the collector able to get all past data, say last 5 years? or is it at the time of implementation forward?

**Comment by Mijago** [comment]
It can not look into the past, sadly.

**Comment by DeFlanko** [comment]
ok, so then i think its working as expected. 👍 


If I change the date range down to say the past hour, i see data. 
![image](https://user-images.githubusercontent.com/5233969/232255682-57fbb93e-afa2-4598-ba75-a3b176efde11.png)


But if one sets it to say **5 years**... it looks like its broken. 
![image](https://user-images.githubusercontent.com/5233969/232255702-cbbdb684-6509-44a6-aad1-aa7bc19caa82.png)



Going to close this out to "User expectations were too high".  xD

**Comment by Mijago** [comment]
That is due to Grafana setting the _interval to something huge if you set it to "past 5 years" :)
Give it a few weeks, and you will see beautiful charts!
