### ISSUE TITLE
UI for InfluxDB

### ISSUE THREAD

**Issue by DeFlanko** [Mijago/D2StatCollector#15]
Im not able to connect to the WebUI of the influxDB installed though this process (http://d2stat-influxdb:8086/) -- i was hoping that i could get to some sort of data dictionary to start making more Grafina charts. 

is there any way to get to the Web Ui of influxDB?

**Comment by DeFlanko** [comment]
i think this could be resolved if we used InfluxDB v2

#6

**Comment by Mijago** [comment]
For documentation I wanted to note that influxdb 1.8 does not have a webui.
